version: "3.9"

networks:
  proxylampy:
    driver: overlay
    external: true
  serverlampy:
    driver: overlay
    external: true

volumes:
  traefik_certs:
  portainer_data:
  mariadb_data:
  postgresql_data:

services:
  mercure:
    image: dunglas/mercure:v0.18
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      ALLOW_ANONYMOUS: "1"
      PUBLISH_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_ORIGINS: "*"
    networks:
      - serverlampy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  redis:
    image: redis:7.4.2
    networks:
      - serverlampy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
  mariadb:
    image: mariadb:11.4.2
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - type: bind
        source: ./mariadb_init
        target: /docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
      - type: bind
        source: ./dump
        target: /dump
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: ingress
    networks:
      - serverlampy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
  postgresql:
    image: postgres:17.2
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - type: bind
        source: ./postgresql_init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./dump
        target: /dump
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: ingress
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    networks:
      - serverlampy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"
  mailtest:
    image: axllent/mailpit:v1.22
    networks:
      - serverlampy
      - proxylampy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxylampy"
        - "traefik.http.routers.mailtest.rule=Host(`mailtest.traefik.me`)"
        - "traefik.http.routers.mailtest-tls.tls.domains[0].main=mailtest.traefik.me"
        - "traefik.http.routers.mailtest.tls=true"
        - "traefik.http.services.mailtest.loadbalancer.server.port=8025"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - serverlampy
      - proxylampy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxylampy"
        - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.traefik.me`)"
        - "traefik.http.routers.phpmyadmin-tls.tls.domains[0].main=phpmyadmin.traefik.me"
        - "traefik.http.routers.phpmyadmin.tls=true"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
  portainer:
    image: portainer/portainer-ce:2.26.1
    networks:
      - proxylampy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxylampy"
        - "traefik.http.routers.portainer.rule=Host(`portainer.traefik.me`)"
        - "traefik.http.routers.portainer-tls.tls.domains[0].main=portainer.traefik.me"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  reverse:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik && wget traefik.me/cert.pem -O cert.pem && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - traefik_certs:/etc/ssl/traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  traefik:
    image: traefik:v3.3.2
    environment:
      TZ: Europe/Paris
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    networks:
      - proxylampy
    volumes:
      - type: bind
        source: ./config/letsencrypt
        target: /letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./config/traefik/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        source: ./config/traefik/middlewares.yml
        target: /etc/traefik/middlewares.yml
      - traefik_certs:/etc/ssl/traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxylampy"
        - "traefik.http.routers.proxy.rule=Host(`proxy.traefik.me`)"
        - "traefik.http.routers.proxy-tls.tls.domains[0].main=proxy.traefik.me"
        - "traefik.http.routers.proxy.tls=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"