api:
  dashboard: true
  debug: true
  insecure: true
providers:
  file:
    filename: /etc/traefik/tls.yml
  docker:
    exposedByDefault: true
    swarmMode: true
    network: proxylampy
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"
entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'