api:
  dashboard: true
  debug: true
  insecure: true
core:
  defaultRuleSyntax: v2
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
log:
  level: DEBUG
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    swarmMode: true
    network: proxylampy
    watch: true
  file:
    filename: /etc/traefik/middlewares.yml
    watch: true
tls:
  certificates:
  - certFile: /etc/ssl/traefik/cert.pem
    keyFile: /etc/ssl/traefik/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/cert.pem
        keyFile: /etc/ssl/traefik/privkey.pem
