api:
  dashboard: true
  debug: true
  insecure: true
core:
  defaultRuleSyntax: v2
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
log:
  level: DEBUG
providers:
  docker:
    swarmMode: true
    network: proxylampy
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: true
    defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"
  file:
    filename: /etc/traefik/tls.yml
  swarm:
    network: proxylampy